package com.hongxin.entity;
// Generated 2016-8-1 11:24:19 by Hibernate Tools 4.3.1.Final

/**
 * FlActionFun generated by hbm2java
 */
public class ActionFun implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String actionId;
	private String sourceId;
	private String code;
	private String func;
	private String funcName;
	private String funcUrl;

	public ActionFun() {
	}

	public ActionFun(String actionId, String sourceId, String code, String func, String funcName, String funcUrl) {
		this.actionId = actionId;
		this.sourceId = sourceId;
		this.code = code;
		this.func = func;
		this.funcName = funcName;
		this.funcUrl = funcUrl;
	}

	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public String getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	public String getFuncName() {
		return this.funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	public String getFuncUrl() {
		return this.funcUrl;
	}

	public void setFuncUrl(String funcUrl) {
		this.funcUrl = funcUrl;
	}

}
