package com.hongxin.entity;
// Generated 2016-4-18 15:48:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * EmployStaff generated by hbm2java
 */
public class EmployStaffDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String staffId;
	private String employeeId;
	private String englishName;
	private String fullName;
	private String idNumber;
	private String sex;
	private String birthday;
	private String nationId;
	private String natives;
	private String policyId;
	private String height;
	private String weight;
	private String telephone;
	private String address;
	private String educationId;
	private String major;
	private String stutas;
	private String marriageId;
	private String stateId;
	private String diseaseInfo;
	private String disabilityInfo;
	private String stationCode;
	private String gradeCode;
	private String stationDate;
	private String cardId;
	private String urgentContact;
	private String urgentTelephone;
	private String urgentRelation;
	private String calculateWages;
	private String picPath;
	private String cardPath;
	private String updateTime;
	private String updator;
	private String bankPath;
	private String wagesType;
	private String creator;
	private Date createTime;
	private String createIp;
	private String updateIp;
	private String remark;
	public String getStaffId() {
		return staffId;
	}
	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}
	public String getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}
	public String getEnglishName() {
		return englishName;
	}
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}
	public String getFullName() {
		return fullName;
	}
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	public String getIdNumber() {
		return idNumber;
	}
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	public String getNationId() {
		return nationId;
	}
	public void setNationId(String nationId) {
		this.nationId = nationId;
	}
	public String getNatives() {
		return natives;
	}
	public void setNatives(String natives) {
		this.natives = natives;
	}
	public String getPolicyId() {
		return policyId;
	}
	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}
	public String getHeight() {
		return height;
	}
	public void setHeight(String height) {
		this.height = height;
	}
	public String getWeight() {
		return weight;
	}
	public void setWeight(String weight) {
		this.weight = weight;
	}
	public String getTelephone() {
		return telephone;
	}
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getEducationId() {
		return educationId;
	}
	public void setEducationId(String educationId) {
		this.educationId = educationId;
	}
	public String getMajor() {
		return major;
	}
	public void setMajor(String major) {
		this.major = major;
	}
	public String getStutas() {
		return stutas;
	}
	public void setStutas(String stutas) {
		this.stutas = stutas;
	}
	public String getMarriageId() {
		return marriageId;
	}
	public void setMarriageId(String marriageId) {
		this.marriageId = marriageId;
	}
	public String getStateId() {
		return stateId;
	}
	public void setStateId(String stateId) {
		this.stateId = stateId;
	}
	public String getDiseaseInfo() {
		return diseaseInfo;
	}
	public void setDiseaseInfo(String diseaseInfo) {
		this.diseaseInfo = diseaseInfo;
	}
	public String getDisabilityInfo() {
		return disabilityInfo;
	}
	public void setDisabilityInfo(String disabilityInfo) {
		this.disabilityInfo = disabilityInfo;
	}
	public String getStationCode() {
		return stationCode;
	}
	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}
	public String getGradeCode() {
		return gradeCode;
	}
	public void setGradeCode(String gradeCode) {
		this.gradeCode = gradeCode;
	}
	public String getStationDate() {
		return stationDate;
	}
	public void setStationDate(String stationDate) {
		this.stationDate = stationDate;
	}
	public String getCardId() {
		return cardId;
	}
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}
	public String getUrgentContact() {
		return urgentContact;
	}
	public void setUrgentContact(String urgentContact) {
		this.urgentContact = urgentContact;
	}
	public String getUrgentTelephone() {
		return urgentTelephone;
	}
	public void setUrgentTelephone(String urgentTelephone) {
		this.urgentTelephone = urgentTelephone;
	}
	public String getUrgentRelation() {
		return urgentRelation;
	}
	public void setUrgentRelation(String urgentRelation) {
		this.urgentRelation = urgentRelation;
	}
	public String getCalculateWages() {
		return calculateWages;
	}
	public void setCalculateWages(String calculateWages) {
		this.calculateWages = calculateWages;
	}
	public String getPicPath() {
		return picPath;
	}
	public void setPicPath(String picPath) {
		this.picPath = picPath;
	}
	public String getCardPath() {
		return cardPath;
	}
	public void setCardPath(String cardPath) {
		this.cardPath = cardPath;
	}
	public String getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}
	public String getUpdator() {
		return updator;
	}
	public void setUpdator(String updator) {
		this.updator = updator;
	}
	public String getBankPath() {
		return bankPath;
	}
	public void setBankPath(String bankPath) {
		this.bankPath = bankPath;
	}
	public String getWagesType() {
		return wagesType;
	}
	public void setWagesType(String wagesType) {
		this.wagesType = wagesType;
	}
	public String getCreator() {
		return creator;
	}
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public String getCreateIp() {
		return createIp;
	}
	public void setCreateIp(String createIp) {
		this.createIp = createIp;
	}
	public String getUpdateIp() {
		return updateIp;
	}
	public void setUpdateIp(String updateIp) {
		this.updateIp = updateIp;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
