package com.hongxin.entity;
// Generated 2016-8-1 17:00:34 by Hibernate Tools 4.3.1.Final

/**
 * FlRoleActionFun generated by hbm2java
 */
public class RoleActionFun implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3055746247588945955L;
	private String roleFuncId;
	private String actionId;
	private String roleId;

	public RoleActionFun() {
	}

	public RoleActionFun(String roleFuncId, String actionId) {
		this.roleFuncId = roleFuncId;
		this.actionId = actionId;
	}

	public RoleActionFun(String roleFuncId, String actionId, String roleId) {
		this.roleFuncId = roleFuncId;
		this.actionId = actionId;
		this.roleId = roleId;
	}

	public String getRoleFuncId() {
		return this.roleFuncId;
	}

	public void setRoleFuncId(String roleFuncId) {
		this.roleFuncId = roleFuncId;
	}

	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
