package com.hongxin.entity;
// Generated 2016-8-1 17:00:34 by Hibernate Tools 4.3.1.Final

/**
 * FlRoleSource generated by hbm2java
 */
public class RoleSource implements java.io.Serializable {
	private static final long serialVersionUID = -1745801240991585107L;
	private String roleSourceId;
	private String sourceId;
	private String roleId;

	public RoleSource() {
	}

	public RoleSource(String roleSourceId) {
		this.roleSourceId = roleSourceId;
	}

	public RoleSource(String roleSourceId, String sourceId, String roleId) {
		this.roleSourceId = roleSourceId;
		this.sourceId = sourceId;
		this.roleId = roleId;
	}

	public String getRoleSourceId() {
		return this.roleSourceId;
	}

	public void setRoleSourceId(String roleSourceId) {
		this.roleSourceId = roleSourceId;
	}

	public String getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
