package com.hongxin.entity;
// Generated 2016-6-3 15:46:26 by Hibernate Tools 4.3.1.Final

/**
 * TBackAcct generated by hbm2java
 */
public class TBackAcct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String pactId;
	private double rebuyAmount;
	private double backAmount;
	private String state;
	private String remark1;
	private String remark2;
	private TPactInfo pactInfo;
	

	public TPactInfo getPactInfo() {
		return pactInfo;
	}

	public void setPactInfo(TPactInfo pactInfo) {
		this.pactInfo = pactInfo;
	}

	public TBackAcct() {
	}

	public TBackAcct(String pactId, double rebuyAmount, double backAmount, String state) {
		this.pactId = pactId;
		this.rebuyAmount = rebuyAmount;
		this.backAmount = backAmount;
		this.state = state;
	}

	public TBackAcct(String pactId, double rebuyAmount, double backAmount, String state, String remark1,
			String remark2) {
		this.pactId = pactId;
		this.rebuyAmount = rebuyAmount;
		this.backAmount = backAmount;
		this.state = state;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getPactId() {
		return this.pactId;
	}

	public void setPactId(String pactId) {
		this.pactId = pactId;
	}

	public double getRebuyAmount() {
		return this.rebuyAmount;
	}

	public void setRebuyAmount(double rebuyAmount) {
		this.rebuyAmount = rebuyAmount;
	}

	public double getBackAmount() {
		return this.backAmount;
	}

	public void setBackAmount(double backAmount) {
		this.backAmount = backAmount;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

}
