package com.hongxin.entity;
// Generated 2016-6-16 13:21:34 by Hibernate Tools 4.3.1.Final

/**
 * TErrCode generated by hbm2java
 */
public class TErrCode implements java.io.Serializable {

	private String sysName;
	private String errCode;
	private String errMsg;
	private String errInfo;
	private String remark1;
	private String remark2;

	public TErrCode() {
	}

	public TErrCode(String sysName, String errCode) {
		this.sysName = sysName;
		this.errCode = errCode;
	}

	public TErrCode(String sysName, String errCode, String errMsg, String errInfo, String remark1, String remark2) {
		this.sysName = sysName;
		this.errCode = errCode;
		this.errMsg = errMsg;
		this.errInfo = errInfo;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	public String getErrCode() {
		return this.errCode;
	}

	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public String getErrInfo() {
		return this.errInfo;
	}

	public void setErrInfo(String errInfo) {
		this.errInfo = errInfo;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

}
