package com.hongxin.entity;
// Generated 2016-5-4 10:43:29 by Hibernate Tools 4.3.1.Final

/**
 * TFundInfo generated by hbm2java
 */
public class TFundInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String workDate;
	private double funds;
	public String getWorkDate() {
		return workDate;
	}
	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}
	public double getFunds() {
		return funds;
	}
	public void setFunds(double funds) {
		this.funds = funds;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}



}
