package com.hongxin.entity;
// Generated 2016-6-16 13:21:34 by Hibernate Tools 4.3.1.Final

/**
 * TFuyouTran generated by hbm2java
 */
public class TFuyouTran implements java.io.Serializable {

	private String fuyouTran;
	private String mchntCd;
	private String mchntTxnSsn;
	private String custNm;
	private String mobileNo;
	private String certifId;
	private String email;
	private String cityId;
	private String parentBankId;
	private String bankNm;
	private String outCustNo;
	private String inCustNo;
	private Double amt;
	private String contractNo;
	private String respCode;
	private String sendMsg;
	private String remark1;
	private String remark2;

	public TFuyouTran() {
	}

	public TFuyouTran(String fuyouTran, String mchntCd, String mchntTxnSsn) {
		this.fuyouTran = fuyouTran;
		this.mchntCd = mchntCd;
		this.mchntTxnSsn = mchntTxnSsn;
	}

	public TFuyouTran(String fuyouTran, String mchntCd, String mchntTxnSsn, String custNm, String mobileNo,
			String certifId, String email, String cityId, String parentBankId, String bankNm, String outCustNo,
			String inCustNo, Double amt, String contractNo, String respCode, String sendMsg, String remark1,
			String remark2) {
		this.fuyouTran = fuyouTran;
		this.mchntCd = mchntCd;
		this.mchntTxnSsn = mchntTxnSsn;
		this.custNm = custNm;
		this.mobileNo = mobileNo;
		this.certifId = certifId;
		this.email = email;
		this.cityId = cityId;
		this.parentBankId = parentBankId;
		this.bankNm = bankNm;
		this.outCustNo = outCustNo;
		this.inCustNo = inCustNo;
		this.amt = amt;
		this.contractNo = contractNo;
		this.respCode = respCode;
		this.sendMsg = sendMsg;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getFuyouTran() {
		return this.fuyouTran;
	}

	public void setFuyouTran(String fuyouTran) {
		this.fuyouTran = fuyouTran;
	}

	public String getMchntCd() {
		return this.mchntCd;
	}

	public void setMchntCd(String mchntCd) {
		this.mchntCd = mchntCd;
	}

	public String getMchntTxnSsn() {
		return this.mchntTxnSsn;
	}

	public void setMchntTxnSsn(String mchntTxnSsn) {
		this.mchntTxnSsn = mchntTxnSsn;
	}

	public String getCustNm() {
		return this.custNm;
	}

	public void setCustNm(String custNm) {
		this.custNm = custNm;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getCertifId() {
		return this.certifId;
	}

	public void setCertifId(String certifId) {
		this.certifId = certifId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getParentBankId() {
		return this.parentBankId;
	}

	public void setParentBankId(String parentBankId) {
		this.parentBankId = parentBankId;
	}

	public String getBankNm() {
		return this.bankNm;
	}

	public void setBankNm(String bankNm) {
		this.bankNm = bankNm;
	}

	public String getOutCustNo() {
		return this.outCustNo;
	}

	public void setOutCustNo(String outCustNo) {
		this.outCustNo = outCustNo;
	}

	public String getInCustNo() {
		return this.inCustNo;
	}

	public void setInCustNo(String inCustNo) {
		this.inCustNo = inCustNo;
	}

	public Double getAmt() {
		return this.amt;
	}

	public void setAmt(Double amt) {
		this.amt = amt;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	public String getSendMsg() {
		return this.sendMsg;
	}

	public void setSendMsg(String sendMsg) {
		this.sendMsg = sendMsg;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

}
