package com.hongxin.entity;
// Generated 2016-6-16 13:21:34 by Hibernate Tools 4.3.1.Final

/**
 * TPactSeq generated by hbm2java
 */
public class TPactSeq implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String seqId;
	private String pactId;
	private String productId;
	private String productName;
	private String takeEff;
	private String lostEff;
	private char seqType;
	private String repayAccout;
	private String payerAccout;
	private Double amount;
	private String bussDate;
	private String bussTime;
	private Character seqStart;
	private String restCode;
	private String restMsg;
	private String remark1;
	private String remark2;

	public TPactSeq() {
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getSeqId() {
		return seqId;
	}

	public void setSeqId(String seqId) {
		this.seqId = seqId;
	}

	public String getPactId() {
		return pactId;
	}

	public void setPactId(String pactId) {
		this.pactId = pactId;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getTakeEff() {
		return takeEff;
	}

	public void setTakeEff(String takeEff) {
		this.takeEff = takeEff;
	}

	public String getLostEff() {
		return lostEff;
	}

	public void setLostEff(String lostEff) {
		this.lostEff = lostEff;
	}

	public char getSeqType() {
		return seqType;
	}

	public void setSeqType(char seqType) {
		this.seqType = seqType;
	}

	public String getRepayAccout() {
		return repayAccout;
	}

	public void setRepayAccout(String repayAccout) {
		this.repayAccout = repayAccout;
	}

	public String getPayerAccout() {
		return payerAccout;
	}

	public void setPayerAccout(String payerAccout) {
		this.payerAccout = payerAccout;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getBussDate() {
		return bussDate;
	}

	public void setBussDate(String bussDate) {
		this.bussDate = bussDate;
	}

	public String getBussTime() {
		return bussTime;
	}

	public void setBussTime(String bussTime) {
		this.bussTime = bussTime;
	}

	public Character getSeqStart() {
		return seqStart;
	}

	public void setSeqStart(Character seqStart) {
		this.seqStart = seqStart;
	}

	public String getRestCode() {
		return restCode;
	}

	public void setRestCode(String restCode) {
		this.restCode = restCode;
	}

	public String getRestMsg() {
		return restMsg;
	}

	public void setRestMsg(String restMsg) {
		this.restMsg = restMsg;
	}

	public String getRemark1() {
		return remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
}
