package com.hongxin.entity;
// Generated 2016-5-9 20:51:44 by Hibernate Tools 4.3.1.Final

/**
 * TProductInfo generated by hbm2java
 */
public class TProductInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String productId;
	private String parentProductId;
	private String productName;
	private String productDesc;
	private String productType;
	private String settleWay;
	private double rateFix;
	private double rateFloat;
	private double rateOth;
	private String recruitmentDate;
	private Double recruitmentFix;
	private String recruitmentState;
	private String initIndex;
	private String realIndex;
	private String takeEff;
	private String lostEff;
	private String createDate;
	private String createTime;
	private String companyName;
	private String companyCode;
	private String bankNo;
	private String bankAccout;
	private String fuyouAccout;
	private String productCycle;
	private String productFcycle;
	private Double amount;
	private double startingAmount;
	private double increasingAmount;
	private String remark1;
	private String remark2;

	public TProductInfo() {
	}

	public TProductInfo(String productId, String productName, String productType, String settleWay, double rateFix,
			double rateFloat, double rateOth, String takeEff, String lostEff, String companyCode, String bankNo,
			String bankAccout, String fuyouAccout, String productCycle, double startingAmount,
			double increasingAmount) {
		this.productId = productId;
		this.productName = productName;
		this.productType = productType;
		this.settleWay = settleWay;
		this.rateFix = rateFix;
		this.rateFloat = rateFloat;
		this.rateOth = rateOth;
		this.takeEff = takeEff;
		this.lostEff = lostEff;
		this.companyCode = companyCode;
		this.bankNo = bankNo;
		this.bankAccout = bankAccout;
		this.fuyouAccout = fuyouAccout;
		this.productCycle = productCycle;
		this.startingAmount = startingAmount;
		this.increasingAmount = increasingAmount;
	}

	public TProductInfo(String productId, String parentProductId, String productName, String productDesc,
			String productType, String settleWay, double rateFix, double rateFloat, double rateOth, String recruitmentDate,
			Double recruitmentFix, String recruitmentState, String initIndex, String realIndex, String takeEff,
			String lostEff, String createDate, String createTime, String companyName, String companyCode, String bankNo,
			String bankAccout, String fuyouAccout, String productCycle, String productFcycle, Double amount,
			double startingAmount, double increasingAmount, String remark1, String remark2) {
		this.productId = productId;
		this.parentProductId = parentProductId;
		this.productName = productName;
		this.productDesc = productDesc;
		this.productType = productType;
		this.settleWay = settleWay;
		this.rateFix = rateFix;
		this.rateFloat = rateFloat;
		this.rateOth = rateOth;
		this.recruitmentDate = recruitmentDate;
		this.recruitmentFix = recruitmentFix;
		this.recruitmentState = recruitmentState;
		this.initIndex = initIndex;
		this.realIndex = realIndex;
		this.takeEff = takeEff;
		this.lostEff = lostEff;
		this.createDate = createDate;
		this.createTime = createTime;
		this.companyName = companyName;
		this.companyCode = companyCode;
		this.bankNo = bankNo;
		this.bankAccout = bankAccout;
		this.fuyouAccout = fuyouAccout;
		this.productCycle = productCycle;
		this.productFcycle = productFcycle;
		this.amount = amount;
		this.startingAmount = startingAmount;
		this.increasingAmount = increasingAmount;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getParentProductId() {
		return this.parentProductId;
	}

	public void setParentProductId(String parentProductId) {
		this.parentProductId = parentProductId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getSettleWay() {
		return this.settleWay;
	}

	public void setSettleWay(String settleWay) {
		this.settleWay = settleWay;
	}

	public double getRateFix() {
		return this.rateFix;
	}

	public void setRateFix(double rateFix) {
		this.rateFix = rateFix;
	}

	public double getRateFloat() {
		return this.rateFloat;
	}

	public void setRateFloat(double rateFloat) {
		this.rateFloat = rateFloat;
	}

	public double getRateOth() {
		return this.rateOth;
	}

	public void setRateOth(double rateOth) {
		this.rateOth = rateOth;
	}

	public String getRecruitmentDate() {
		return this.recruitmentDate;
	}

	public void setRecruitmentDate(String recruitmentDate) {
		this.recruitmentDate = recruitmentDate;
	}

	public Double getRecruitmentFix() {
		return this.recruitmentFix;
	}

	public void setRecruitmentFix(Double recruitmentFix) {
		this.recruitmentFix = recruitmentFix;
	}

	public String getRecruitmentState() {
		return this.recruitmentState;
	}

	public void setRecruitmentState(String recruitmentState) {
		this.recruitmentState = recruitmentState;
	}

	public String getInitIndex() {
		return this.initIndex;
	}

	public void setInitIndex(String initIndex) {
		this.initIndex = initIndex;
	}

	public String getRealIndex() {
		return this.realIndex;
	}

	public void setRealIndex(String realIndex) {
		this.realIndex = realIndex;
	}

	public String getTakeEff() {
		return this.takeEff;
	}

	public void setTakeEff(String takeEff) {
		this.takeEff = takeEff;
	}

	public String getLostEff() {
		return this.lostEff;
	}

	public void setLostEff(String lostEff) {
		this.lostEff = lostEff;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public String getBankAccout() {
		return this.bankAccout;
	}

	public void setBankAccout(String bankAccout) {
		this.bankAccout = bankAccout;
	}

	public String getFuyouAccout() {
		return this.fuyouAccout;
	}

	public void setFuyouAccout(String fuyouAccout) {
		this.fuyouAccout = fuyouAccout;
	}

	public String getProductCycle() {
		return this.productCycle;
	}

	public void setProductCycle(String productCycle) {
		this.productCycle = productCycle;
	}

	public String getProductFcycle() {
		return this.productFcycle;
	}

	public void setProductFcycle(String productFcycle) {
		this.productFcycle = productFcycle;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public double getStartingAmount() {
		return this.startingAmount;
	}

	public void setStartingAmount(double startingAmount) {
		this.startingAmount = startingAmount;
	}

	public double getIncreasingAmount() {
		return this.increasingAmount;
	}

	public void setIncreasingAmount(double increasingAmount) {
		this.increasingAmount = increasingAmount;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

}
