package com.hongxin.entity;
// Generated 2016-6-16 13:21:34 by Hibernate Tools 4.3.1.Final

/**
 * TSysHolidays generated by hbm2java
 */
public class TSysHolidays implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String holidays;
	private char flags;
	private String remark;

	public TSysHolidays() {
	}

	public TSysHolidays(String holidays, char flags, String remark) {
		this.holidays = holidays;
		this.flags = flags;
		this.remark = remark;
	}

	public String getHolidays() {
		return this.holidays;
	}

	public void setHolidays(String holidays) {
		this.holidays = holidays;
	}

	public char getFlags() {
		return this.flags;
	}

	public void setFlags(char flags) {
		this.flags = flags;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
