package com.hongxin.entity;
// Generated 2016-4-18 15:48:18 by Hibernate Tools 4.3.1.Final
/**
 * 用户登录类
 * @author gaojun
 * gaojun6854@126.com
 */
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;//用户ID
	private String userName;//用户名
	private String userType;//用户类型
	private String employeeId;//员工号
	private String password;//密码
	private String orgId;///组织id
	private String email;//邮箱
	private String mobiePhone;//手机号
	private Integer isLocked;//是否锁定
	private Integer isEnable;//是否可用
	private String randNum;//验证随机数
	private Date expireTime;//随机数失效时间
	private Integer requirePasswordChange;//请求改变密码次数
	private String lastLocale;//上一次登录地址
	private Date lastLoginDate;//上一次登录时间
	private String operrationUserId;//操作id
	private Date createDate;//创建时间
	private Date updateDate;//更新时间
	private String remark;//备注

	private EmployStaff employStaff;
	private Organization oeganization; 
	private Map<String,ResourceBak> resourceBak;//用户拥有的菜单
	private List<UsrRole> userole;
	
	
	public Organization getOeganization() {
		return oeganization;
	}

	public void setOeganization(Organization oeganization) {
		this.oeganization = oeganization;
	}

	public Map<String, ResourceBak> getResourceBak() {
		return resourceBak;
	}

	public void setResourceBak(Map<String, ResourceBak> resourceBak) {
		this.resourceBak = resourceBak;
	}

	public List<UsrRole> getUserole() {
		return userole;
	}

	public void setUserole(List<UsrRole> userole) {
		this.userole = userole;
	}

	public EmployStaff getEmployStaff() {
		return employStaff;
	}

	public void setEmployStaff(EmployStaff employStaff) {
		this.employStaff = employStaff;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public User() {
	}

	public User(String userId, String userName, String password, Date lastLoginDate, String operrationUserId,
			Date createDate) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.lastLoginDate = lastLoginDate;
		this.operrationUserId = operrationUserId;
		this.createDate = createDate;
	}

	public User(String userId, String userName, String userType, String employeeId, String password, String orgId,
			String email, String mobiePhone, Integer isLocked, Integer isEnable, String randNum, Date expireTime,
			Integer requirePasswordChange, String lastLocale, Date lastLoginDate, String operrationUserId,
			Date createDate, Date updateDate, String remark) {
		this.userId = userId;
		this.userName = userName;
		this.userType = userType;
		this.employeeId = employeeId;
		this.password = password;
		this.orgId = orgId;
		this.email = email;
		this.mobiePhone = mobiePhone;
		this.isLocked = isLocked;
		this.isEnable = isEnable;
		this.randNum = randNum;
		this.expireTime = expireTime;
		this.requirePasswordChange = requirePasswordChange;
		this.lastLocale = lastLocale;
		this.lastLoginDate = lastLoginDate;
		this.operrationUserId = operrationUserId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobiePhone() {
		return this.mobiePhone;
	}

	public void setMobiePhone(String mobiePhone) {
		this.mobiePhone = mobiePhone;
	}

	public Integer getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(Integer isLocked) {
		this.isLocked = isLocked;
	}

	public Integer getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Integer isEnable) {
		this.isEnable = isEnable;
	}

	public String getRandNum() {
		return this.randNum;
	}

	public void setRandNum(String randNum) {
		this.randNum = randNum;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Integer getRequirePasswordChange() {
		return this.requirePasswordChange;
	}

	public void setRequirePasswordChange(Integer requirePasswordChange) {
		this.requirePasswordChange = requirePasswordChange;
	}

	public String getLastLocale() {
		return this.lastLocale;
	}

	public void setLastLocale(String lastLocale) {
		this.lastLocale = lastLocale;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getOperrationUserId() {
		return this.operrationUserId;
	}

	public void setOperrationUserId(String operrationUserId) {
		this.operrationUserId = operrationUserId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
