package com.hongxin.entity;
// Generated 2016-8-1 17:27:52 by Hibernate Tools 4.3.1.Final

import java.util.List;

/**
 * FlUsrRole generated by hbm2java
 */
public class UsrRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3013731601198082310L;
	private String usrRoleId;
	private String userId;
	private String roleId;
	private List<Role> roles;
	public UsrRole() {
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public UsrRole(String usrRoleId) {
		this.usrRoleId = usrRoleId;
	}

	public UsrRole(String usrRoleId, String userId, String roleId) {
		this.usrRoleId = usrRoleId;
		this.userId = userId;
		this.roleId = roleId;
	}

	public String getUsrRoleId() {
		return this.usrRoleId;
	}

	public void setUsrRoleId(String usrRoleId) {
		this.usrRoleId = usrRoleId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
