package com.hongxin.entity;

// Generated 2016-2-24 22:43:49 by Hibernate Tools 3.4.0.CR1

/**
 * TCheckInfoId generated by hbm2java
 */
public class CheckInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String checkId;
	private Integer checkSer;
	private String checkSec;
	private Character checkType;
	private String othId;
	private Character checkFlow;
	private String custName;
	private String paperType;
	private String paperNum;
	private String productId;
	private String checkManNum;
	private String checkManName;
	private Character checkStart;
	private String checkOpinion;
	private String checkDesc;
	private String cehckRecId;
	private String createDate;
	private String createTime;
	private String remark1;
	private String remark2;
	private CustomBaseInfo customBaseInfo;
	

	public CustomBaseInfo getCustomBaseInfo() {
		return customBaseInfo;
	}

	public void setCustomBaseInfo(CustomBaseInfo customBaseInfo) {
		this.customBaseInfo = customBaseInfo;
	}

	public CheckInfo() {
	}

	public CheckInfo(String checkId, Integer checkSer, String checkSec,
			Character checkType, String othId, Character checkFlow,
			String custName, String paperType, String paperNum,
			String productId, String checkManNum, String checkManName,
			Character checkStart, String checkOpinion, String checkDesc,
			String cehckRecId, String createDate, String createTime,
			String remark1, String remark2) {
		this.checkId = checkId;
		this.checkSer = checkSer;
		this.checkSec = checkSec;
		this.checkType = checkType;
		this.othId = othId;
		this.checkFlow = checkFlow;
		this.custName = custName;
		this.paperType = paperType;
		this.paperNum = paperNum;
		this.productId = productId;
		this.checkManNum = checkManNum;
		this.checkManName = checkManName;
		this.checkStart = checkStart;
		this.checkOpinion = checkOpinion;
		this.checkDesc = checkDesc;
		this.cehckRecId = cehckRecId;
		this.createDate = createDate;
		this.createTime = createTime;
		this.remark1 = remark1;
		this.remark2 = remark2;
	}

	public String getCheckId() {
		return this.checkId;
	}

	public void setCheckId(String checkId) {
		this.checkId = checkId;
	}

	public Integer getCheckSer() {
		return this.checkSer;
	}

	public void setCheckSer(Integer checkSer) {
		this.checkSer = checkSer;
	}

	public String getCheckSec() {
		return this.checkSec;
	}

	public void setCheckSec(String checkSec) {
		this.checkSec = checkSec;
	}

	public Character getCheckType() {
		return this.checkType;
	}

	public void setCheckType(Character checkType) {
		this.checkType = checkType;
	}

	public String getOthId() {
		return this.othId;
	}

	public void setOthId(String othId) {
		this.othId = othId;
	}

	public Character getCheckFlow() {
		return this.checkFlow;
	}

	public void setCheckFlow(Character checkFlow) {
		this.checkFlow = checkFlow;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getPaperType() {
		return this.paperType;
	}

	public void setPaperType(String paperType) {
		this.paperType = paperType;
	}

	public String getPaperNum() {
		return this.paperNum;
	}

	public void setPaperNum(String paperNum) {
		this.paperNum = paperNum;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getCheckManNum() {
		return this.checkManNum;
	}

	public void setCheckManNum(String checkManNum) {
		this.checkManNum = checkManNum;
	}

	public String getCheckManName() {
		return this.checkManName;
	}

	public void setCheckManName(String checkManName) {
		this.checkManName = checkManName;
	}

	public Character getCheckStart() {
		return this.checkStart;
	}

	public void setCheckStart(Character checkStart) {
		this.checkStart = checkStart;
	}

	public String getCheckOpinion() {
		return this.checkOpinion;
	}

	public void setCheckOpinion(String checkOpinion) {
		this.checkOpinion = checkOpinion;
	}

	public String getCheckDesc() {
		return this.checkDesc;
	}

	public void setCheckDesc(String checkDesc) {
		this.checkDesc = checkDesc;
	}

	public String getCehckRecId() {
		return this.cehckRecId;
	}

	public void setCehckRecId(String cehckRecId) {
		this.cehckRecId = cehckRecId;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheckInfo))
			return false;
		CheckInfo castOther = (CheckInfo) other;

		return ((this.getCheckId() == castOther.getCheckId()) || (this
				.getCheckId() != null && castOther.getCheckId() != null && this
				.getCheckId().equals(castOther.getCheckId())))
				&& ((this.getCheckSer() == castOther.getCheckSer()) || (this
						.getCheckSer() != null
						&& castOther.getCheckSer() != null && this
						.getCheckSer().equals(castOther.getCheckSer())))
				&& ((this.getCheckSec() == castOther.getCheckSec()) || (this
						.getCheckSec() != null
						&& castOther.getCheckSec() != null && this
						.getCheckSec().equals(castOther.getCheckSec())))
				&& ((this.getCheckType() == castOther.getCheckType()) || (this
						.getCheckType() != null
						&& castOther.getCheckType() != null && this
						.getCheckType().equals(castOther.getCheckType())))
				&& ((this.getOthId() == castOther.getOthId()) || (this
						.getOthId() != null && castOther.getOthId() != null && this
						.getOthId().equals(castOther.getOthId())))
				&& ((this.getCheckFlow() == castOther.getCheckFlow()) || (this
						.getCheckFlow() != null
						&& castOther.getCheckFlow() != null && this
						.getCheckFlow().equals(castOther.getCheckFlow())))
				&& ((this.getCustName() == castOther.getCustName()) || (this
						.getCustName() != null
						&& castOther.getCustName() != null && this
						.getCustName().equals(castOther.getCustName())))
				&& ((this.getPaperType() == castOther.getPaperType()) || (this
						.getPaperType() != null
						&& castOther.getPaperType() != null && this
						.getPaperType().equals(castOther.getPaperType())))
				&& ((this.getPaperNum() == castOther.getPaperNum()) || (this
						.getPaperNum() != null
						&& castOther.getPaperNum() != null && this
						.getPaperNum().equals(castOther.getPaperNum())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())))
				&& ((this.getCheckManNum() == castOther.getCheckManNum()) || (this
						.getCheckManNum() != null
						&& castOther.getCheckManNum() != null && this
						.getCheckManNum().equals(castOther.getCheckManNum())))
				&& ((this.getCheckManName() == castOther.getCheckManName()) || (this
						.getCheckManName() != null
						&& castOther.getCheckManName() != null && this
						.getCheckManName().equals(castOther.getCheckManName())))
				&& ((this.getCheckStart() == castOther.getCheckStart()) || (this
						.getCheckStart() != null
						&& castOther.getCheckStart() != null && this
						.getCheckStart().equals(castOther.getCheckStart())))
				&& ((this.getCheckOpinion() == castOther.getCheckOpinion()) || (this
						.getCheckOpinion() != null
						&& castOther.getCheckOpinion() != null && this
						.getCheckOpinion().equals(castOther.getCheckOpinion())))
				&& ((this.getCheckDesc() == castOther.getCheckDesc()) || (this
						.getCheckDesc() != null
						&& castOther.getCheckDesc() != null && this
						.getCheckDesc().equals(castOther.getCheckDesc())))
				&& ((this.getCehckRecId() == castOther.getCehckRecId()) || (this
						.getCehckRecId() != null
						&& castOther.getCehckRecId() != null && this
						.getCehckRecId().equals(castOther.getCehckRecId())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this
						.getCreateTime() != null
						&& castOther.getCreateTime() != null && this
						.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getRemark1() == castOther.getRemark1()) || (this
						.getRemark1() != null && castOther.getRemark1() != null && this
						.getRemark1().equals(castOther.getRemark1())))
				&& ((this.getRemark2() == castOther.getRemark2()) || (this
						.getRemark2() != null && castOther.getRemark2() != null && this
						.getRemark2().equals(castOther.getRemark2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCheckId() == null ? 0 : this.getCheckId().hashCode());
		result = 37 * result
				+ (getCheckSer() == null ? 0 : this.getCheckSer().hashCode());
		result = 37 * result
				+ (getCheckSec() == null ? 0 : this.getCheckSec().hashCode());
		result = 37 * result
				+ (getCheckType() == null ? 0 : this.getCheckType().hashCode());
		result = 37 * result
				+ (getOthId() == null ? 0 : this.getOthId().hashCode());
		result = 37 * result
				+ (getCheckFlow() == null ? 0 : this.getCheckFlow().hashCode());
		result = 37 * result
				+ (getCustName() == null ? 0 : this.getCustName().hashCode());
		result = 37 * result
				+ (getPaperType() == null ? 0 : this.getPaperType().hashCode());
		result = 37 * result
				+ (getPaperNum() == null ? 0 : this.getPaperNum().hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37
				* result
				+ (getCheckManNum() == null ? 0 : this.getCheckManNum()
						.hashCode());
		result = 37
				* result
				+ (getCheckManName() == null ? 0 : this.getCheckManName()
						.hashCode());
		result = 37
				* result
				+ (getCheckStart() == null ? 0 : this.getCheckStart()
						.hashCode());
		result = 37
				* result
				+ (getCheckOpinion() == null ? 0 : this.getCheckOpinion()
						.hashCode());
		result = 37 * result
				+ (getCheckDesc() == null ? 0 : this.getCheckDesc().hashCode());
		result = 37
				* result
				+ (getCehckRecId() == null ? 0 : this.getCehckRecId()
						.hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37
				* result
				+ (getCreateTime() == null ? 0 : this.getCreateTime()
						.hashCode());
		result = 37 * result
				+ (getRemark1() == null ? 0 : this.getRemark1().hashCode());
		result = 37 * result
				+ (getRemark2() == null ? 0 : this.getRemark2().hashCode());
		return result;
	}

}
