package com.hongxin.entity;
// Generated 2016-4-18 15:48:18 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.hongxin.service.EmployStaffService;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String orgId;
	private Organization parentOrganization;
	private String orgName;
	private Integer seq;
	private String createTime;
	private String creator;
	private Date updateDate;
	private String operationIp;
	private String orgValue;
	private Set<Organization>organizations=new HashSet<Organization>(0);
	private Set<EmployStaff> employStaffs = new HashSet<EmployStaff>(0);
	private List<Organization>childOrganization=new ArrayList<Organization>();
	private List<EmployStaff>employStaffs2=new ArrayList<EmployStaff>();
	public String getOrgId() {
		return orgId;
	}
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
	public Organization getParentOrganization() {
		return parentOrganization;
	}
	public void setParentOrganization(Organization parentOrganization) {
		this.parentOrganization = parentOrganization;
	}
	public String getOrgName() {
		return orgName;
	}
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	public Integer getSeq() {
		return seq;
	}
	public void setSeq(Integer seq) {
		this.seq = seq;
	}
	public String getCreateTime() {
		return createTime;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getCreator() {
		return creator;
	}
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	public String getOperationIp() {
		return operationIp;
	}
	public void setOperationIp(String operationIp) {
		this.operationIp = operationIp;
	}
	public String getOrgValue() {
		return orgValue;
	}
	public void setOrgValue(String orgValue) {
		this.orgValue = orgValue;
	}
	public Set<Organization> getOrganizations() {
		return organizations;
	}
	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}
	public Set<EmployStaff> getEmployStaffs() {
		return employStaffs;
	}
	public void setEmployStaffs(Set<EmployStaff> employStaffs) {
		this.employStaffs = employStaffs;
	}
	public List<Organization> getChildOrganization() {
		return childOrganization;
	}
	public void setChildOrganization(List<Organization> childOrganization) {
		this.childOrganization = childOrganization;
	}
	public List<EmployStaff> getEmployStaffs2() {
		return employStaffs2;
	}
	public void setEmployStaffs2(List<EmployStaff> employStaffs2) {
		this.employStaffs2 = employStaffs2;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}
